package Treex::Block::HamleDT::Test::UD::ToDoBug;
use Moose;
use Treex::Core::Common;
extends 'Treex::Block::Test::BaseTester';

sub process_anode
{
    my $self = shift;
    my $node = shift;
    my $wild = $node->wild();
    my @misc;
    @misc = split(/\|/, $wild->{misc}) if(exists($wild->{misc}) && defined($wild->{misc}));
    if (any {m/^(Bug|ToDo)=/} (@misc))
    {
        $self->complain($node, 'Bug or ToDo from Udapi');
    }
}

1;

=encoding utf-8

=head1 NAME

Treex::Block::HamleDT::Test::UD::ToDoBug

=head1 DESCRIPTION

Just reports nodes that already have a Bug or ToDo label in MISC generated by Udapi.

=head1 AUTHOR

Dan Zeman <zeman@ufal.mff.cuni.cz>

=head1 COPYRIGHT AND LICENSE

Copyright © 2017 by Institute of Formal and Applied Linguistics,
Charles University in Prague

This module is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
