package Treex::Tutorial::Config;

=pod

=encoding utf8

=head1 NAME

Treex::Tutorial::Config - Configuring Treex


=head1 EXAMPLES

TODO?

=head1 SEE ALSO

L<Treex::Core::Config>

=head1 AUTHOR

Dušan Variš <varis@ufal.mff.cuni.cz>
Martin Popel <popel@ufal.mff.cuni.cz>

=head1 COPYRIGHT AND LICENSE

Copyright © 2011 by Institute of Formal and Applied Linguistics, Charles University in Prague

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

