package Treex::Tutorial::Install;

=pod

=head1 NAME

Treex::Tutorial::Install - Installing the Treex NLP framework

=head1 SYNOPSIS

    # 1. Prepare local Perl enviroment, so Perl modules will be installed to ~/perl5.
    # If you have a root access and want to install to system paths, skip this step.
    wget -O- http://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
    eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
    echo 'eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`' >> ~/.bashrc

    # 2. Install Treex::Core and its dependencies from CPAN.
    # Instead of "cpanm" tool, you can use "cpan" if you wish.
    cpanm Treex::Core
    treex -h # just to check if it was installed

    # 3. Install Treex modules for processing English
    cpanm Treex::EN

    # 4. (optional) Download the newest version of whole Treex from SVN repository.
    cd ~
    svn --username public co https://svn.ms.mff.cuni.cz/svn/tectomt_devel/trunk/treex treex
    # password is "public"
    # Add the following line to your ~/.bashrc
    export PATH="$HOME/treex/bin:$PATH"
    export PERL5LIB="$HOME/treex/lib:$PERL5LIB"

    # 5. (optional) Install TrEd (tree viewer and editor)
    # see http://ufal.mff.cuni.cz/tred/

=head1 AUTHOR

Martin Popel <popel@ufal.mff.cuni.cz>

=head1 COPYRIGHT AND LICENSE

Copyright © 2011 by Institute of Formal and Applied Linguistics, Charles University in Prague

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
