
vectors:
	treex -p -j 100 -Len Read::Treex from='@/net/cluster/TMP/czeng10/filelist_parsed_train' A2A::ConvertTags input_driver=en::penn A2A::EN::EnhanceInterset Util::Eval anode='$$.set_tag($$.iset->pos)' Print::VectorsForTreeLM path=vectors/
