package Treex::Tool::Lexicon::UniversalTagset;

use Moose;
use Treex::Core::Common;

my $mappings = {
    'cs' => {
        '*' => 'NUM',
        ',' => 'CONJ',
        '1' => 'PRON',
        '2' => 'ADJ',
        '4' => 'PRON',
        '5' => 'PRON',
        '6' => 'PRON',
        '7' => 'PRON',
        '8' => 'PRON',
        '9' => 'PRON',
        ':' => '.',
        '=' => 'NUM',
        '?' => 'NUM',
        '@' => 'X',
        'A' => 'ADJ',
        'B' => 'VERB',
        'C' => 'ADJ',
        'D' => 'PRON',
        'E' => 'PRON',
        'F' => 'ADP',
        'G' => 'ADJ',
        'H' => 'PRON',
        'I' => 'X',
        'J' => 'PRON',
        'K' => 'PRON',
        'L' => 'PRON',
        'M' => 'ADJ',
        'N' => 'NOUN',
        'O' => 'PRON',
        'P' => 'PRON',
        'Q' => 'PRON',
        'R' => 'PRON',
        'S' => 'ADP',
        'T' => 'PRT',
        'U' => 'ADJ',
        'V' => 'ADP',
        'W' => 'PRON',
        'X' => 'X',
        'Z' => 'PRON',
        '^' => 'CONJ',
        'a' => 'NUM',
        'b' => 'ADV',
        'c' => 'VERB',
        'd' => 'NUM',
        'e' => 'VERB',
        'f' => 'VERB',
        'g' => 'ADV',
        'h' => 'NUM',
        'i' => 'VERB',
        'k' => 'NUM',
        'l' => 'NUM',
        'm' => 'VERB',
        'n' => 'NUM',
        'o' => 'NUM',
        'p' => 'VERB',
        'r' => 'NUM',
        's' => 'VERB',
        'u' => 'NUM',
        'v' => 'NUM',
        'w' => 'NUM',
        'x' => 'X',
        'y' => 'NUM',
        '}' => 'NUM',
    },
    'en' => {
        '!' => '.',
        '#' => '.',
        '$' => '.',
        '\'\'' => '.',
        '(' => '.',
        ')' => '.',
        ',' => '.',
        '-LRB-' => '.',
        '-RRB-' => '.',
        '.' => '.',
        ':' => '.',
        '?' => '.',
        'CC' => 'CONJ',
        'CD' => 'NUM',
        'CD|RB' => 'X',
        'DT' => 'DET',
        'EX' => 'DET',
        'FW' => 'X',
        'IN' => 'ADP',
        'IN|RP' => 'ADP',
        'JJ' => 'ADJ',
        'JJR' => 'ADJ',
        'JJRJR' => 'ADJ',
        'JJS' => 'ADJ',
        'JJ|RB' => 'ADJ',
        'JJ|VBG' => 'ADJ',
        'LS' => 'X',
        'MD' => 'VERB',
        'NN' => 'NOUN',
        'NNP' => 'NOUN',
        'NNPS' => 'NOUN',
        'NNS' => 'NOUN',
        'NN|NNS' => 'NOUN',
        'NN|SYM' => 'NOUN',
        'NN|VBG' => 'NOUN',
        'NP' => 'NOUN',
        'PDT' => 'DET',
        'POS' => 'PRT',
        'PRP' => 'PRON',
        'PRP$' => 'PRON',
        'PRP|VBP' => 'PRON',
        'PRT' => 'PRT',
        'RB' => 'ADV',
        'RBR' => 'ADV',
        'RBS' => 'ADV',
        'RB|RP' => 'ADV',
        'RB|VBG' => 'ADV',
        'RN' => 'X',
        'RP' => 'PRT',
        'SYM' => 'X',
        'TO' => 'PRT',
        'UH' => 'X',
        'VB' => 'VERB',
        'VBD' => 'VERB',
        'VBD|VBN' => 'VERB',
        'VBG' => 'VERB',
        'VBG|NN' => 'VERB',
        'VBN' => 'VERB',
        'VBP' => 'VERB',
        'VBP|TO' => 'VERB',
        'VBZ' => 'VERB',
        'VP' => 'VERB',
        'WDT' => 'DET',
        'WH' => 'X',
        'WP' => 'PRON',
        'WP$' => 'PRON',
        'WRB' => 'ADV',
        '``' => '.',
    },
};

sub convert_tag {
    my ($tag, $language) = @_;
    my $utag;
    if ($language eq 'cs') {
        return $tag if (length($tag) < 2);
        my $subpos = substr($tag, 1, 1);
        $utag = $mappings->{$language}{$subpos};
    }
    if ($language eq 'en') {
        $utag = $mappings->{$language}{$tag};
    }
    return $tag if (!defined $utag);
    return $utag;
}

1;
